ALTER TABLE therapy_settings
  ADD COLUMN IF NOT EXISTS note_1_visible BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS note_2_visible BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS note_3_visible BOOLEAN NOT NULL DEFAULT TRUE;
